# Generated by Django 3.1.14 on 2023-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('like', models.BooleanField()),
                ('comment', models.TextField(max_length=120, null=True)),
                ('stop_code', models.TextField(max_length=30)),
                ('stop_id', models.TextField(max_length=30, null=True)),
                ('route_id', models.TextField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'feedback_brt',
            },
        ),
    ]
