# Generated by Django 3.1.14 on 2023-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackbrt',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
