# Generated by Django 3.1.14 on 2023-01-27 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedianModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id_origin', models.CharField(blank=True, max_length=500)),
                ('stop_id_destiny', models.CharField(blank=True, max_length=500)),
                ('tipo_dia', models.CharField(blank=True, max_length=500)),
                ('hora', models.IntegerField()),
                ('delta_secs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=500)),
                ('stop_id', models.CharField(max_length=500)),
                ('id_veiculo', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dataHora', models.CharField(max_length=500)),
                ('trip_short_name', models.CharField(max_length=500)),
                ('direction_id', models.CharField(max_length=500)),
                ('service_id', models.CharField(max_length=500)),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShapesWithStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_short_name', models.CharField(blank=True, max_length=500, null=True)),
                ('direction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service_id', models.CharField(max_length=500)),
                ('trip_id', models.CharField(blank=True, max_length=500)),
                ('stop_sequence', models.PositiveIntegerField()),
                ('stop_id', models.CharField(blank=True, max_length=500)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shape_id', models.CharField(blank=True, max_length=500)),
                ('shape_pt_sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('next_stop_id', models.CharField(max_length=500)),
                ('previous_stop_id', models.CharField(max_length=500)),
            ],
        ),
    ]
