# Generated by Django 3.1.14 on 2023-01-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShapeWithStops',
            new_name='ShapesWithStops',
        ),
    ]
