# Generated by Django 3.1.14 on 2023-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictorReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_json', models.JSONField(null=True)),
            ],
        ),
    ]
