# Generated by Django 3.1.14 on 2023-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeswithstops',
            name='next_stop_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapeswithstops',
            name='previous_stop_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
