# Generated by Django 3.1.14 on 2023-01-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='arrival_time',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
