# Generated by Django 3.1.14 on 2023-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20230131_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
