# Generated by Django 3.1.14 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20230127_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapeswithstops',
            old_name='shape_pt_lat',
            new_name='latitude',
        ),
    ]
