# Generated by Django 3.1.14 on 2023-03-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictorreturn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictorReturn',
            new_name='PredictorResult',
        ),
        migrations.RenameField(
            model_name='predictorresult',
            old_name='return_json',
            new_name='result_json',
        ),
    ]
