# Generated by Django 3.1.14 on 2023-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20230313_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictorresult',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
