# Generated by Django 3.1.14 on 2023-02-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20230131_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='id_veiculo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
