# Generated by Django 3.1.14 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20230127_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapeswithstops',
            old_name='shape_pt_lon',
            new_name='longitude',
        ),
    ]
