# Generated by Django 3.1.14 on 2023-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20230127_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeswithstops',
            name='direction_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
