# Generated by Django 3.1.14 on 2023-02-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20230131_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='arrival_time',
            field=models.DurationField(null=True),
        ),
    ]
