# Generated by Django 3.1.14 on 2022-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_type',
            field=models.CharField(choices=[('0', 'VLT'), ('1', 'Trem e metrô municipais'), ('2', 'Trem e metrô intermunicipais'), ('3', 'Ônibus'), ('4', 'Barcas'), ('5', 'Bonde'), ('6', 'Teleférico'), ('7', 'Funicular'), ('11', 'Ônibus elétrico'), ('12', 'Monotrilho')], max_length=500),
        ),
    ]
