# Generated by Django 3.1.14 on 2022-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
