# Generated by Django 3.1.14 on 2022-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='bikes_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 'informação não disponível'), (1, 'permitido'), (2, 'não permitido')], null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='wheelchair_accessible',
            field=models.IntegerField(blank=True, choices=[(0, 'informação não disponível'), (1, 'acessível'), (2, 'não acessível')], null=True),
        ),
    ]
