# Generated by Django 3.1.14 on 2022-11-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='route_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pontos.routes'),
        ),
    ]
