# Generated by Django 3.1.14 on 2023-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='arrival_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='departure_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
