# Generated by Django 3.1.14 on 2022-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='continuous_drop_off',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'embarque com paradas contínuas'), (1, 'nenhum embarque com paradas contínuas'), (2, 'agendar embarque com paradas contínuas'), (3, 'combinar agendamento com o motorista')], default=1, null=True),
        ),
    ]
