# Generated by Django 3.1.14 on 2022-12-07 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapes',
            name='shape_dist_traveled',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shapes',
            name='shape_pt_sequence',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='stops',
            constraint=models.UniqueConstraint(fields=('stop_id', 'stop_code'), name='stop_code_id'),
        ),
    ]
