# Generated by Django 3.1.14 on 2023-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20230306_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='departure_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
