# Generated by Django 3.1.13 on 2021-07-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20210726_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='long_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
