# Generated by Django 3.1.14 on 2022-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20221206_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
