# Generated by Django 3.1.14 on 2022-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20221206_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='continuous_drop_off',
            field=models.IntegerField(blank=True, choices=[(0, 'embarque com paradas contínuas'), (1, 'nenhum embarque com paradas contínuas'), (2, 'agendar embarque com paradas contínuas'), (3, 'combinar agendamento com o motorista')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='continuous_pickup',
            field=models.IntegerField(blank=True, choices=[(0, 'embarque com paradas contínuas'), (1, 'nenhum embarque com paradas contínuas'), (2, 'agendar embarque com paradas contínuas'), (3, 'combinar agendamento com o motorista')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='service_id',
            field=models.CharField(max_length=500),
        ),
    ]
