# Generated by Django 3.1.14 on 2022-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20221129_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='friday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='monday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='saturday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sunday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thursday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='tuesday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='wednesday',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
