# Generated by Django 3.1.14 on 2022-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_auto_20221207_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='stops',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, location_type__in=[0, 1, 2]), models.Q(('stop_lat__isnull', False), ('stop_lon__isnull', False)), _connector='OR'), name='stop_lat_lon'),
        ),
    ]
