# Generated by Django 3.1.14 on 2022-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0003_auto_20221206_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='agency_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
