# Generated by Django 3.1.14 on 2024-10-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0003_auto_20230306_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareAttributes',
            fields=[
                ('fare_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_type', models.CharField(max_length=3)),
                ('payment_method', models.IntegerField(choices=[(0, 'on board'), (1, 'before boarding')])),
                ('transfers', models.IntegerField(blank=True, choices=[(0, 'No transfers'), (1, 'One transfer'), (2, 'Two transfers')], null=True)),
                ('transfer_duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fare Attribute',
                'verbose_name_plural': 'Fare Attributes',
            },
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.CharField(max_length=255)),
                ('feed_publisher_url', models.URLField()),
                ('feed_lang', models.CharField(max_length=10)),
                ('default_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('feed_start_date', models.DateField(blank=True, null=True)),
                ('feed_end_date', models.DateField(blank=True, null=True)),
                ('feed_version', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feed_contact_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feed Information',
                'verbose_name_plural': 'Feed Information',
            },
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelOptions(
            name='calendardates',
            options={'verbose_name': 'Calendar date', 'verbose_name_plural': 'Calendar dates'},
        ),
        migrations.AlterModelOptions(
            name='frequencies',
            options={'verbose_name': 'Frequency', 'verbose_name_plural': 'Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='shapes',
            options={'verbose_name': 'Shape', 'verbose_name_plural': 'Shapes'},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'verbose_name': 'Stop time', 'verbose_name_plural': 'Stop times'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.CreateModel(
            name='FareRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contains_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.fareattributes')),
                ('route_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pontos.routes')),
            ],
            options={
                'verbose_name': 'Fare Rule',
                'verbose_name_plural': 'Fare Rules',
            },
        ),
        migrations.AddField(
            model_name='fareattributes',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pontos.agency'),
        ),
    ]
