# Generated by Django 3.1.14 on 2022-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0003_auto_20221129_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
