# Generated by Django 3.1.14 on 2022-12-07 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_auto_20221207_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='wheelchair_boarding',
            field=models.IntegerField(blank=True, choices=[(0, 'information not available'), (1, 'available'), (2, 'not available')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
