# Generated by Django 3.1.14 on 2022-12-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_auto_20221206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='agency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.agency'),
        ),
    ]
