# Generated by Django 3.1.14 on 2022-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_auto_20221206_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='direction_id',
            field=models.IntegerField(blank=True, choices=[(0, 'ida'), (1, 'volta')], max_length=500, null=True),
        ),
    ]
