# Generated by Django 3.1.13 on 2021-07-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_auto_20210726_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
