# Generated by Django 3.1.13 on 2021-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0005_auto_20210726_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='direction',
            field=models.IntegerField(default=0),
        ),
    ]
