# Generated by Django 3.1.14 on 2022-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0005_auto_20221207_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='level_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
