# Generated by Django 3.1.14 on 2022-12-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0005_auto_20221206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_short_name',
            field=models.CharField(max_length=500),
        ),
    ]
