# Generated by Django 3.1.13 on 2021-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0006_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
