# Generated by Django 3.1.14 on 2022-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0006_auto_20221206_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_long_name',
            field=models.CharField(max_length=500),
        ),
    ]
