# Generated by Django 3.1.13 on 2021-07-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0009_auto_20210726_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
