# Generated by Django 3.1.13 on 2021-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0010_auto_20210726_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
