# Generated by Django 3.1.13 on 2021-11-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0012_auto_20211108_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
