# Generated by Django 3.1.14 on 2022-11-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0015_auto_20221104_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop_times',
            old_name='order',
            new_name='stop_sequence',
        ),
    ]
